### ISSUE TITLE
Charts not visible - All pages

### ISSUE THREAD

**Issue by app-generator** [app-generator/adminator-v2#3]
### Homepage Original

![image](https://user-images.githubusercontent.com/51070104/183234105-7f63722e-dcf5-4179-b902-f6342b2957a0.png)

### Adminator v2

![image](https://user-images.githubusercontent.com/51070104/183234121-265390b4-3252-4ba7-ac82-8cec4905520d.png)

**Comment by 9sumit** [comment]
Chart Not Visible - All pages solved.

**Comment by app-generator** [comment]
Validated. Ty @9sumit
